version: "3.8"
services:
  api:
    build:
      context: .
      args:
        node_image: node:16-alpine
    ports:
      - "${API_PORT}:3000"
    environment:
      - NODE_ENV=development
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - DB_HOST=host.docker.internal
      - KEYCLOAK_HOST=host.docker.internal
