version: "3.8"
services:
  api:
    build:
      context: .
      args:
        node_image: node:16-alpine
    ports:
      - "${API_PORT}:3001"
    depends_on:
      - keycloak
    environment:
      - NODE_ENV=development
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - DB_HOST=host.docker.internal
      - KEYCLOAK_HOST=host.docker.internal

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://host.docker.internal:5432/keycloakdb
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=password
      - KC_HOSTNAME=localhost
    depends_on:
      - postgres
    command:
      - start-dev

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=keycloakdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./scripts/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
volumes:
  pg_data: