### get access token for crete keycloak user
POST {{base_url_keycloak}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id={{client_id}}&client_secret={{client_secret}}&grant_type=client_credentials

> {%
client.global.set("admin_access_token", response.body.access_token);
%}

### create keycloak user
POST {{base_url_keycloak}}/admin/realms/{{realm}}/users
Content-Type: application/json
Authorization: Bearer {{admin_access_token}}

{
  "enabled": true,
  "username": "username",
  "credentials": [
    {
      "type": "password",
      "value": "password",
      "temporary": false
    }
  ]
}

### send-verify-email
PUT {{base_url_keycloak}}/admin/realms/{{realm}}/users/{{user_id}}/send-verify-email
Authorization: Bearer {{admin_access_token}}
