### create new appointment
POST {{base_url_bff}}/api/appointments
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "creatorId": "1",
  "title": "标题",
  "introduction": "内容",
  "startTime": "2023-04-07T17:00:00+08:00",
  "endTime": "2023-04-07T17:30:00+08:00",
  "departmentIds": [
    1
  ]
}

### get users
GET {{base_url_bff}}/api/appointments
